apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.applicationName}}
spec:
  selector:
    matchLabels:
      app: {{.Values.applicationName}}
  template:
    metadata:
      labels:
        app: {{.Values.applicationName}}
    spec:
      containers:
        - name: incubation-rendezvous
          image: "harbor.fumo.jp/private/incubation-rendezvous:{{.Values.tag}}"
          ports:
            - containerPort: 8000
