template: tcardgen/template.png
title:
  start:
    px: 150
    py: 150
  fgHexColor: "#403b3b"
  fontSize: 72
  fontStyle: Bold
  maxWidth: 900
  lineSpacing: 10
category:
  start:
    px: 9999  # hidden
    py: 9999  # hidden
  fgHexColor: "#EEF4ED"  # hidden
  fontSize: 38
  fontStyle: Regular
info:
  start:
    px: 250
    py: 480
  fgHexColor: "#403b3b"
  fontSize: 38
  fontStyle: Regular
  separator: " - "
tags:
  start:
    px: 9999  # hidden
    py: 9999  # hidden
  fgHexColor: "#EEF4ED"  # hidden
  bgHexColor: "#134074"
  fontSize: 22
  fontStyle: Medium
  boxAlign: Right
  boxSpacing: 10
